version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    # networks:
    #   - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    # networks:
    #   - app-network
    environment:
      - REACT_APP_API_URL=https://hback.readiy.tech

# networks:
#   app-network:
#     driver: bridge
